#!/usr/bin/env php
<?php
// bin/doctrine

use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Doctrine\ORM\Tools\Console\EntityManagerProvider\SingleManagerProvider;

// Adjust this path to your actual bootstrap.php
// Doctrine ORM
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\ORMSetup;

require __DIR__. '/vendor/autoload.php';

// Create a simple "default" Doctrine ORM configuration for Attributes
$config = ORMSetup::createAttributeMetadataConfiguration(
    paths: array(__DIR__ . "/entity"),
    isDevMode: true,
);

$conn = array(
    'driver'   => 'pdo_mysql',
    'host'     => '127.0.0.1',
    'user'     => 'root',
    'password' => '',
    'dbname'   => 'dashboard',
    'port'     => 3306,
    'charset'  => 'utf8',
);

// obtaining the entity manager
$entityManager = EntityManager::create($conn, $config);

ConsoleRunner::run(
    new SingleManagerProvider($entityManager)
);

